language: go
go:
  - master
before_install:
  - cat $GOOGLE_CREDENTIALS_VALUE > ./Google-Credentials.json
script:
  - go test -cover
after_success:
  - go build -a --installsuffix cgo --ldflags="-s" -o matryoshka
