language: go
go:
  - master
before_install:
  - echo $GOOGLE_CREDENTIALS_VALUE > $TRAVIS_BUILD_DIR/$GOOGLE_APPLICATION_CREDENTIALS
script:
  - go test -cover
after_success:
  - go build -a --installsuffix cgo --ldflags="-s" -o matryoshka
